name: Positron Academy Story Bot

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests Pillow

      - name: Run Auto Story Bot
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          IG_ACCOUNT_ID: ${{ secrets.IG_ACCOUNT_ID }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: python bot.py

      - name: Save Progress
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add posted.txt
          git commit -m "Progress update [Skip CI]" || exit 0
          git push
